sudo: required

language: node.js

install:
  - npm ci

script:
  - npm test

before_deploy:
  - npm run build

deploy:
  local-dir: output
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
